/**
 * Checkpoint and versioning types for Claude Agent
 */

import type { Message } from './message';
import type { FileChange } from './file';

export interface Checkpoint {
  id: string;
  parentId: string | null;
  childIds: string[];
  timestamp: number;
  title: string;
  description: string;
  filesChanged: FileChange[];
  conversationSnapshot: Message[];
  metadata: CheckpointMetadata;
}

export interface CheckpointMetadata {
  branch: string;
  commitSha: string;
  isActive: boolean;
  tags?: string[];
  autoGenerated: boolean;
}

export interface ICheckpointTree {
  root: string | null;
  nodes: Record<string, Checkpoint>;
  currentId: string | null;
  activeLineage: string[];
}

// Alias for backwards compatibility
export type CheckpointTreeData = ICheckpointTree;

export interface CheckpointGroup {
  label: string;
  checkpoints: Checkpoint[];
}