// ============================================================================
// Core Types for Claude Agent
// ============================================================================

// ----------------------------------------------------------------------------
// Message Types
// ----------------------------------------------------------------------------

export type MessageRole = 'user' | 'assistant' | 'system';

export type ContextItemType = 'file' | 'selection' | 'url' | 'image';

export interface ContextItem {
  id: string;
  type: ContextItemType;
  name: string;        // Display name (filename, URL title, etc.)
  path?: string;       // Full path for files
  content?: string;    // File content, selection text, etc. (loaded lazily)
  preview?: string;    // Short preview snippet
  metadata?: Record<string, unknown>; // Line range, language, etc.
}

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: number;
  context?: ContextItem[];
  toolCalls?: ToolCall[];
  toolResults?: ToolResult[];
  isStreaming?: boolean;
  checkpointCommitHash?: string;
}

export interface ToolCall {
  id: string;
  name: string;
  input: Record<string, unknown>;
  status: 'pending' | 'running' | 'completed' | 'error';
  output?: string;
}

export interface ToolResult {
  toolCallId: string;
  output: string;
  isError: boolean;
}

// ----------------------------------------------------------------------------
// File Types
// ----------------------------------------------------------------------------

export type FileChangeType = 'added' | 'modified' | 'deleted' | 'renamed';

export interface FileChange {
  path: string;
  type: FileChangeType;
  oldPath?: string; // For renames
  additions: number;
  deletions: number;
  diff?: string;
}

export interface FileNode {
  name: string;
  path: string;
  type: 'file' | 'directory';
  children?: FileNode[];
  changeType?: FileChangeType;
}

// ----------------------------------------------------------------------------
// Checkpoint Types
// ----------------------------------------------------------------------------

export interface Checkpoint {
  id: string;
  parentId: string | null;
  childIds: string[];
  timestamp: number;
  title: string;
  description: string;
  filesChanged: FileChange[];
  conversationSnapshot: Message[];
  metadata: CheckpointMetadata;
}

export interface CheckpointMetadata {
  branch: string;
  commitSha: string;
  isActive: boolean;
  tags?: string[];
  autoGenerated: boolean;
}

export interface ICheckpointTree {
  root: string | null;
  nodes: Record<string, Checkpoint>;
  currentId: string | null;
  activeLineage: string[];
}

// Alias for backwards compatibility
export type CheckpointTreeData = ICheckpointTree;

export interface CheckpointGroup {
  label: string;
  checkpoints: Checkpoint[];
}

// ----------------------------------------------------------------------------
// Git Types (simplified for UI)
// ----------------------------------------------------------------------------

export interface GitBranch {
  name: string;
  current: boolean;
  commit: string;
  label: string;
  lastCommitDate?: string;
}

export interface GitCommit {
  hash: string;
  hashShort: string;
  message: string;
  body: string;
  date: string;
  timestamp: number;
  authorName: string;
  authorEmail: string;
  filesChanged: number;
}

// ----------------------------------------------------------------------------
// Session Types
// ----------------------------------------------------------------------------

export interface Session {
  id: string;
  name: string;
  branch: string;
  projectPath: string;
  createdAt: number;
  lastActive: number;
  checkpointIds: string[];
  isActive: boolean;
}

export interface ChatSession {
  id: string;
  branch: string;
  branchName: string;
  name: string;
  messages: Message[];
  createdAt: number;
  lastActive: number;
}

// ----------------------------------------------------------------------------
// Project Types
// ----------------------------------------------------------------------------

export interface Project {
  id: string;
  name: string;
  path: string;
  lastOpened: number;
  createdAt: number;
  checkpointTree: ICheckpointTree;
  sessions: Session[];
  activeSessionId: string | null;
  settings: ProjectSettings;
}

export interface ProjectSettings {
  autoCheckpoint: boolean;
  checkpointOnToolCall: boolean;
  maxCheckpoints: number;
  gitBranch: string;
}

// ----------------------------------------------------------------------------
// Claude Code Types
// ----------------------------------------------------------------------------

export interface ClaudeConfig {
  workingDir: string;
  model?: string;
  maxTokens?: number;
  systemPrompt?: string;
  allowedTools?: string[];
  dangerouslySkipPermissions?: boolean;
}

// Claude Code CLI stream-json event types (actual format from CLI)
export type ClaudeEventType = 'system' | 'assistant' | 'user' | 'result';

// Content block types within assistant messages
export interface TextContentBlock {
  type: 'text';
  text: string;
}

export interface ToolUseContentBlock {
  type: 'tool_use';
  id: string;
  name: string;
  input: Record<string, unknown>;
}

export interface ToolResultContentBlock {
  type: 'tool_result';
  tool_use_id: string;
  content: string;
  is_error?: boolean;
}

export type ContentBlock = TextContentBlock | ToolUseContentBlock | ToolResultContentBlock;

// Claude Code stream-json event structure
export interface ClaudeSystemEvent {
  type: 'system';
  subtype: 'init';
  session_id: string;
  tools?: string[];
  mcp_servers?: unknown[];
}

export interface ClaudeAssistantEvent {
  type: 'assistant';
  message: {
    content: ContentBlock[];
  };
  partial?: boolean; // Present when using --include-partial-messages
}

export interface ClaudeUserEvent {
  type: 'user';
  message: {
    content: ContentBlock[];
  };
}

export interface ClaudeResultEvent {
  type: 'result';
  subtype: 'success' | 'error';
  session_id?: string;
  cost_usd?: number;
  num_turns?: number;
  result?: string;
  error?: string;
}

export type ClaudeEvent = ClaudeSystemEvent | ClaudeAssistantEvent | ClaudeUserEvent | ClaudeResultEvent;

export interface ClaudeStreamChunk {
  type: 'text' | 'tool_call' | 'tool_result' | 'error' | 'init' | 'complete';
  content: string;
  toolCall?: ToolCall;
  toolResult?: ToolResult;
  sessionId?: string;
}

// ----------------------------------------------------------------------------
// UI State Types
// ----------------------------------------------------------------------------

export interface PanelState {
  isOpen: boolean;
  size: number;
}

export interface LayoutState {
  leftPanel: PanelState;
  rightPanel: PanelState;
  bottomPanel: PanelState;
}

export interface UIState {
  theme: 'light' | 'dark' | 'system';
  layout: LayoutState;
  activeProjectId: string | null;
  selectedCheckpointId: string | null;
  previewCheckpointId: string | null;
}

// ----------------------------------------------------------------------------
// Event Types
// ----------------------------------------------------------------------------

export interface AgentEvents {
  'checkpoint:created': (checkpoint: Checkpoint) => void;
  'checkpoint:restored': (checkpoint: Checkpoint) => void;
  'checkpoint:deleted': (checkpointId: string) => void;
  'message:received': (message: Message) => void;
  'message:streaming': (chunk: ClaudeStreamChunk) => void;
  'tool:started': (toolCall: ToolCall) => void;
  'tool:completed': (toolCall: ToolCall, result: ToolResult) => void;
  'file:changed': (change: FileChange) => void;
  'project:opened': (project: Project) => void;
  'project:closed': (projectId: string) => void;
  'error': (error: Error) => void;
}
